-- local options = {
--   ensure_installed = {
--     -- lua stuff
--     "lua-language-server",
--     "stylua",
--
--
--     -- web dev stuff
--     "css-lsp",
--     "html-lsp",
--     "typescript-language-server",
--     "deno",
--     "prettier",
--
--     -- c/cpp stuff
--     "clangd",
--     "clang-format",
--     "codelldb",
--
--     -- cmake
--     "cmake-language-server",
--     "cmakelang",
--
--     -- latex
--     "vale",
--     "latexindent",
--
--     -- "cspell",
--     "tree-sitter-cli",
--
--     -- python
--     "python-lsp-server",
--     "black",
--     "flake8"
--   },
--   -- PATH = "skip",
--   ui = {
--     check_outdated_packages_on_open = false,
--     border = 'single',
--     icons = {
--       package_pending = " ",
--       package_installed = "󰄳 ",
--       package_uninstalled = " 󰚌",
--     },
--
--     keymaps = {
--       toggle_server_expand = "<CR>",
--       install_server = "i",
--       update_server = "u",
--       check_server_version = "c",
--       update_all_servers = "U",
--       check_outdated_servers = "C",
--       uninstall_server = "X",
--       cancel_installation = "<C-c>",
--     },
--   },
--
--   max_concurrent_installers = 10,
-- }
--
-- return options
